### ISSUE TITLE
Voltz Engine Error on Launch

### ISSUE THREAD

**Issue by Sunboyz21** [BuiltBrokenModding/VoltzEngine#107]
Minecraft Version:
- 1.7.10
Forge Version:
- 1.7.10-Forge10.13.4.1614-1.7.10
VoltzEngine Version:
- VoltzEngine 1.7.10-1.11.0b453-UNSTABLE build 453 for 1.7.10
*is this the latest curseforge build?*
- Yes
**Please Pastebin crash**
- https://paste.ee/p/hXq2N
---------------------
Crash Report:
https://paste.ee/p/Kh0I8
----------
Explain issue in detail: 
So I'm working on a modpack and everything worked fine until I updated the mod versions for VE, Atomic Science, MFFS, Armory, ICBM Classic, and ICBM Classic Sentry.

**Comment by DarkGuardsman** [comment]
`java.lang.NoSuchMethodError: com.builtbroken.mc.framework.json.loading.JsonLoader.addConverter(Lcom/builtbroken/mc/framework/json/conversion/JsonConverter;)V
	at com.builtbroken.armory.Armory.loadJsonContentHandlers(Armory.java:114) ~[Armory.class:1.7.10-0.7.4b132]`

I think someone reported something like this before. Issue turned out to be not running correct VE for the armory version. Best way to do this is to download the alpha of each. 

https://minecraft.curseforge.com/projects/the-armory/files/2579093

**Comment by Sunboyz21** [comment]
That did the trick, thanks so much for the fast reply!
