### ISSUE TITLE
Broken names/textures

### ISSUE THREAD

**Issue by Breadabix** [BuiltBrokenModding/VoltzEngine#88]
Minecraft Version:
1.7.10
Forge Version:
forge-10.13.4.1614
VoltzEngine Version:
VoltzEngine-1.7.10-1.9.9b242

This is the latest curseforge build

There is no crash to post

Explain issue in detail:
Gem textures and names are broken, for both raw/uncut and cut gems.
![2017-09-19_00 04 14](https://user-images.githubusercontent.com/19786108/30568646-2f929e50-9cce-11e7-87ef-b326f0b4ab24.png)

**Comment by DarkGuardsman** [comment]
Known issue, gems are an unfinished addition to the mod

**Comment by Breadabix** [comment]
I have started using the precious version of the mod, VoltzEngine-1.7.10-1.9.4b228, and it isnt an issue. This is the first version of the mod I have used where I have seen this.

**Comment by DarkGuardsman** [comment]
That might be due to the previous version using the same texture with colorization for missing values. The new version has the textures manually set per value via JSON. The plan is to make some textures here soon but there was no priority due to lack of usage of gems.

Either way, thank you for reporting the issue. I'll leave the ticket open until it's fixed :)

**Comment by Breadabix** [comment]
No problem, always happy to help mod authors.

**Comment by Hennamann** [comment]
This is no longer an issue as all the textures should work as well should localization.

**Comment by Breadabix** [comment]
This is still an issue with some gems, specifically gem 0,11,12,13,14,15. https://gyazo.com/6f184f487612e8a202da91dbb863381e
