### ISSUE TITLE
Default ores harvest level are not set

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/VoltzEngine#91]
Minecraft Version:
- 1.7.10
Forge Version:
- n/a
VoltzEngine Version:
- VoltzEngine-1.7.10-1.9.13b270

Explain issue in detail:
All VE ores have basic harvest level: they can be all mined at the same speed, with a stone pickaxe.

Levels should be more progressive, for example:
0- wood tools to mine stone
1- stone tools to mine coal and copper
2- copper tools to mine iron and redstone
3- iron/steel tools to mine lapis, tin and lead + Nickel, Zinc?
4- bronze/lead tools to mine gold, diamond, silver and gems + Uranium?
5- gems/diamond tools to mine obsidian, platinum

**Comment by DarkGuardsman** [comment]
That is because in real life you can mine stone with stone. I find minecraft's mining level BS and frustrating.

**Comment by LemADEC** [comment]
So you want to remove the progression aspect of ores harvesting?
What happen if we want to use VE in a non-BBM modpack?

**Comment by DarkGuardsman** [comment]
Config the harvest levels, its all JSON data

**Comment by LemADEC** [comment]
config/bbm/json is empty for me.
Should I copy the ones inside the VE jar? Where would I put it?
What's the key and values to use for HarvestLevel and HarvestTool?
Can we have different HarvestLevel for each metadata?

**Comment by DarkGuardsman** [comment]
its empty by default as the JSON is stored in the jars. It would be a bad idea to copy all the JSON and then have sticky values from older versions. This is why its implemented via the override system. Which is only half complemented. I will finish setting it up for block data and write a guide sometime this week. 

As for harvest level, it can be set per material and due to custom harvest implementation allows tile entity information to be used. Though this can't be done via JSON at the moment without adding a listener.

**Comment by DarkGuardsman** [comment]
Err rather is should work per material if I finished implementing the code lol

**Comment by DarkGuardsman** [comment]
> So you want to remove the progression aspect of ores harvesting?

Yes and no, I don't like the way most mods handle progress of ores. From a player view its frustrating to run into an ore and not be able to mine it with a tool. Its even more frustrating from a design point of view as there is no valid reason for mining to work that way. I can understand for things like diamonds and obsidian. However, weaker resources should be easy to mine.

This is not just based on my own experience. I've watched a lot of users over the years express problems with the concept. Most just decide to live with it rather than changing the game to match expectations. You can see this via watching lets players when they run into ores. They end up going "Oh I need a better pick" with the tone of there voice being disappointed or unamused.

 As well gating resources via mining levels give people the wrong impression of how mining works. Most of the time you're not breaking the metal, instead, you're freeing the metal from the stone by breaking the stone. I want VE mods to reflect this and thus I have all ores harvest at the same level as stone. A lot of the content added into the game will reflect on this as well.

Additionally, this fits well with MC's logic if you IGNORE other mods. As most of the metals are near iron mining level anyways. Iron can be mined just fine with stone tools. To gate some of the metals at a higher teir because mod X does it is not a valid reason. The only reason to gate an ore would be to balance the game. Which is also just as invalid since it would be better to balance via another mechanic. Such as making the ore harder to process via a machine or multi-step system. This way a user can mine the resource for processing later instead of wasting it to clear a room for building.

**Comment by LemADEC** [comment]
That's your game design, I think it should be written somewhere, like in Voltz design document :)

**Comment by DarkGuardsman** [comment]
lol rarely have time to write all of this down. We have a supermassive gap in documentation and designs. There are concepts going back to 2012 that are planned for VoltzEngine. That is where most of this comes from as I've disliked the concept for a very long time. TBH I dislike gating to creat progression a rather ugly concept. I feel like progression should be free-flowing and dynamic. Allowing a user to enter into a mod from any direction they want..... basicly picture a spider web and you will figure out what I'm thinking.

**Comment by LemADEC** [comment]
Documenting it will help you conceptualize it and help other understand what you're proposing :)
